# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'saveProject.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys
import os , shutil
from PyQt5.QtWidgets import *
from PyQt5.QtCore import Qt
from subprocess import Popen


class ExportProject(QtWidgets.QDialog):

    def __init__(self,Form,ABS_Packager):
        super(ExportProject, self).__init__()
        Form.setObjectName("Form")
        Form.resize(459, 204)
        Form.setMinimumSize(QtCore.QSize(450, 200))
        Form.setStyleSheet("background-color: white")

        self.Projectlabel = QtWidgets.QLabel(Form)
        self.Projectlabel.setGeometry(QtCore.QRect(40, 20, 231, 51))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(18)
        self.Projectlabel.setFont(font)
        self.Projectlabel.setStyleSheet("color: black;")
        self.Projectlabel.setObjectName("Projectlabel")
        
        self.ProjectName = QtWidgets.QLineEdit(Form)
        self.ProjectName.setGeometry(QtCore.QRect(40, 60, 351, 41))
        self.ProjectName.setStyleSheet("color: black;")
        self.ProjectName.setObjectName("ProjectName")


        self.CreateButton = QtWidgets.QPushButton(Form)
        self.CreateButton.setGeometry(QtCore.QRect(40, 120, 161, 41))
        font.setPointSize(11)
        self.CreateButton.setFont(font)
        self.CreateButton.setStyleSheet("background-color: #13333F; color: #FFFFFF; border-radius: 5px; padding: 8px 0px;")
        self.CreateButton.setObjectName("CreateButton")

        self.PackageButton = QtWidgets.QPushButton(Form)
        self.PackageButton.setGeometry(QtCore.QRect(40, 120, 161, 41))
        font.setPointSize(11)
        self.PackageButton.setFont(font)
        self.PackageButton.setStyleSheet("background-color: #13333F; color: #FFFFFF; border-radius: 5px; padding: 8px 0px;")
        self.PackageButton.setObjectName("PackageButton")
        self.PackageButton.hide()
        
        self.CancelButton = QtWidgets.QPushButton(Form)
        self.CancelButton.setGeometry(QtCore.QRect(230, 120, 161, 41))
        font.setPointSize(11)
        self.CancelButton.setFont(font)
        self.CancelButton.setStyleSheet("background-color: #13333F; color: #FFFFFF; border-radius: 5px; padding: 8px 0px;")
        self.CancelButton.setObjectName("CancelButton")

        self.exitButton = QtWidgets.QPushButton(Form)
        self.exitButton.setGeometry(QtCore.QRect(230, 120, 161, 41))
        font.setPointSize(11)
        self.exitButton.setFont(font)
        self.exitButton.setStyleSheet("background-color: #13333F; color: #FFFFFF; border-radius: 5px; padding: 8px 0px;")
        self.exitButton.setObjectName("ExitButton")
        self.exitButton.hide()

        # Error label
        self.error_label = QtWidgets.QLabel("This project already exists")
        self.error_label.setStyleSheet("color: red;")
        self.error_label.setGeometry(QtCore.QRect(40, 120, 250, 51))
        self.error_label.setFont(font)
        self.error_label.setHidden(True)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

        self.project_sP = ""
        self.files = QtWidgets.QListWidget()
        self.VMs = []
   
      
        ########################### BUTTON ACTIONS ##################################
        self.CreateButton.clicked.connect(self.create_folders)
        self.CancelButton.clicked.connect(Form.close)
        self.exitButton.clicked.connect(Form.close)
        self.exitButton.clicked.connect(ABS_Packager.close)
        
    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Export Project"))
        self.Projectlabel.setText(_translate("Form", "Project Name:"))
        self.CreateButton.setText(_translate("Form", "Create Project"))
        self.PackageButton.setText(_translate("Form", "Package"))
        self.CancelButton.setText(_translate("Form", "Cancel"))
        self.exitButton.setText(_translate("Form", "Exit"))

    ################# GATHER FILE AND VM LIST FROM PACKAGER WINDOW ################  
    def pass_objects(self,file_List,VMs):
        self.files = file_List
        self.VMs = VMs
        
    ################# SAVE PROJECT AND CREATE PROJECT FILE STRUCTURE ###############
    def create_folders(self):
        self.error_label.setHidden(True)
        self.project_sP = self.ProjectName.text()
        
        # Create Projects root path if does not exist
        if not os.path.exists("Project Data"):
            os.makedirs("Project Data")

        #  Create Project Paths
        if not os.path.exists("../Project Data/" + self.ProjectName.text()):
            print("creating folders....")
            os.makedirs("Project Data/" + self.ProjectName.text())
            os.makedirs("Project Data/" + self.ProjectName.text() + "/VMs/")
            os.makedirs("Project Data/" + self.ProjectName.text() + "/Files/")
            self.CancelButton.hide()
            self.CreateButton.hide()

            self.PackageButton.show()
            self.PackageButton.clicked.connect(self.copy_files)
            print("Project was created")
            
        else:
            self.error_label.setHidden(False)
            print("Project Name Already Exists")

    ################# COPY FILES AND EXPORT VMS INTO PROJECT DIRECTORY ####################################
    def copy_files(self):
        
        if(self.files.count()>0):
            print("Copying Files into Project......")
        for i in range(self.files.count()):
            print (self.files.item(i).text())
            shutil.copy(self.files.item(i).text(),"Project Data/" + self.ProjectName.text() + "/Files/")
        
        if self.VMs:
            print("Exporting VMs.....")

        a_dir = 'Project Data'
        b_dir = self.ProjectName.text()
        c_dir = 'VMs'   
        
        for i in self.VMs:
            print("Exporting " + i + " Virtual Machine")
            out = os.path.join(a_dir,b_dir,c_dir)
            filename = i+'.ova'
            out = os.path.join(out,filename)
            command_args = ['vboxmanage','export', i,'--output', out]

            proc = Popen(command_args,close_fds=True)

            
            outp, err = proc.communicate()
            if outp:
                print(outp)
            if err:    
                print(err)
            
        self.compress_project()   

    ################# COMPRESS PROJECT FOLDER AND SAVE INTO /PROJECT DATA/ DIRECTORY #######################
    def compress_project(self):
        dirpath = 'Project Data/'
        print("Compressing.......")
        self.PackageButton.hide()
        self.exitButton.show()
        shutil.make_archive(dirpath + self.ProjectName.text(),'zip',dirpath,self.ProjectName.text())
        self.Projectlabel.setText("Finished Packaging")
        print("Done Packaging project " + self.ProjectName.text())

''' 
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = CreateProject(Form)
    Form.show()
    sys.exit(app.exec_())
'''