# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Analyzing_GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QTimer
from PyQt5.QtWidgets import QWidget

import time
import os
from subprocess import Popen,PIPE
import platform
import sys

class Ui_Analyzing_Window(QWidget):

    def setupUi(self, Analyzing_Window):
        Analyzing_Window.setObjectName("Analyzing_Window")
        Analyzing_Window.resize(690, 365)
        Analyzing_Window.setStyleSheet("background-color: white;")
        self.progressBar = QtWidgets.QProgressBar(Analyzing_Window)
        self.progressBar.setGeometry(QtCore.QRect(140, 60, 441, 51))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        self.progressBar.setFont(font)
        self.progressBar.setStyleSheet("QProgressBar {\n"
                                       "    border: 2px solid grey;\n"
                                       "    border-radius: 5px;\n"
                                       "    text-align: center;\n"
                                       "    color: rgb(140, 140, 140);\n"
                                       "}\n"
                                       "\n"
                                       "QProgressBar::chunk {\n"
                                       "    background-color: rgb(19,51,63) ;\n"
                                       "    width: 10px;\n"
                                       "    margin: 0.5px;\n"
                                       "}")
        self.progressBar.setMaximum(100)
        self.progressBar.setTextVisible(True)
        self.progressBar.setObjectName("progressBar")
        self.label = QtWidgets.QLabel(Analyzing_Window)
        self.label.setGeometry(QtCore.QRect(270, 140, 141, 31))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setStyleSheet("color: black;")
        self.label.setObjectName("label")
        self.Time_Elapsed = QtWidgets.QLabel(Analyzing_Window)
        self.Time_Elapsed.setGeometry(QtCore.QRect(150, 190, 101, 16))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        self.Time_Elapsed.setFont(font)
        self.Time_Elapsed.setStyleSheet("color:black;")
        self.Time_Elapsed.setObjectName("Time_Elapsed")
        self.Time_Elapsed_A = QtWidgets.QLabel(Analyzing_Window)
        self.Time_Elapsed_A.setGeometry(QtCore.QRect(300, 190, 71, 16))
        
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        self.Time_Elapsed_A.setFont(font)
        self.Time_Elapsed_A.setStyleSheet("color:black;")
        self.Time_Elapsed_A.setObjectName("Time_Elapsed_A")
        
        self.Commands = QtWidgets.QLabel(Analyzing_Window)
        self.Commands.setGeometry(QtCore.QRect(150, 220, 111, 16))
        
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        self.Commands.setFont(font)
        self.Commands.setStyleSheet("color:black;")
        self.Commands.setObjectName("Commands")
        
        self.Commands_A = QtWidgets.QLabel(Analyzing_Window)
        self.Commands_A.setGeometry(QtCore.QRect(300, 220, 71, 16))
        
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        self.Commands_A.setFont(font)
        self.Commands_A.setStyleSheet("color:black;")
        self.Commands_A.setObjectName("Commands_A")
        
        self.Clicks = QtWidgets.QLabel(Analyzing_Window)
        self.Clicks.setGeometry(QtCore.QRect(150, 250, 111, 16))
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        self.Clicks.setFont(font)
        self.Clicks.setStyleSheet("color:black;")
        self.Clicks.setObjectName("Clicks")
        
        self.Clicks_A = QtWidgets.QLabel(Analyzing_Window)
        self.Clicks_A.setGeometry(QtCore.QRect(300, 250, 71, 16))
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        self.Clicks_A.setFont(font)
        self.Clicks_A.setStyleSheet("color:black;")
        self.Clicks_A.setObjectName("Clicks_A")
   
        self.Export = QtWidgets.QPushButton(Analyzing_Window)
        self.Export.setGeometry(QtCore.QRect(410, 200, 141, 51))
        font.setFamily("MS Sans Serif")
        font.setPointSize(12)
        self.Export.setFont(font)
        self.Export.setStyleSheet("background-color: #13333F; color: #FFFFFF; border-radius: 5px;")
        self.Export.setObjectName("Export")
        self.retranslateUi(Analyzing_Window)
        QtCore.QMetaObject.connectSlotsByName(Analyzing_Window)

        ######################## BUTTON ACTIONS ######################################
        self.Export.clicked.connect(Analyzing_Window.close)
        #self.Export.clicked.connect(CEWindow.close)
        self.Export.clicked.connect(self.open_runner)
        
        ##############################################################################

    def retranslateUi(self, Analyzing_Window):
        _translate = QtCore.QCoreApplication.translate
        Analyzing_Window.setWindowTitle(_translate("Analyzing_Window", "Analyzing.."))
        self.label.setText(_translate("Analyzing_Window", "Analyzing..."))
        self.Time_Elapsed.setText(_translate("Analyzing_Window", "Time Elapsed"))
        self.Time_Elapsed_A.setText(_translate("Analyzing_Window", "0:0:0"))
        self.Commands.setText(_translate("Analyzing_Window", "Commands "))
        self.Commands_A.setText(_translate("Analyzing_Window", "0"))
        self.Clicks.setText(_translate("Analyzing_Window", "Clicks "))
        self.Clicks_A.setText(_translate("Analyzing_Window", "0"))
        self.Export.setText(_translate("Analyzing_Window", "Export to runner"))

    def progressBar_update(self):
        pass

    ######################## OPEN BUILDER ##################################
    def open_runner(self):

        if platform.system() == "Windows":
            Popen(['python', 'GUI_manager.py', 'runner'],stdout=PIPE, stderr=PIPE)
        else:
            Popen(['python3', 'GUI_manager.py', 'runner'],stdout=PIPE, stderr=PIPE)
        
            
    ########################################################################